Modify Pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,14 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-npx lint-staged
+function lintit () {
+  OUTPUT=$(git diff --name-only | grep -E '(.js)$')
+  a=("${(f)OUTPUT}")
+  e=$(eslint -c eslint.json $a)
+  echo $e
+  if [[ "$e" != *"0 problems"* ]]; then
+    echo "ERROR: Check eslint hints."
+    exit 1 # reject
+  fi
+}
+lintit
